swagger: "2.0"
info:
    title: GoTrim API Service
    description: URL shortening service written in Go
    version: 0.0.1
host: localhost:3050
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/v1/shorten:
        post:
            tags:
                - UrlShortener
            summary: CreateShortUrl UrlShortener
            operationId: UrlShortener#CreateShortUrl
            parameters:
                - name: object
                  in: body
                  required: true
                  schema:
                    type: object
                    properties:
                        long_url:
                            type: string
                            description: URL to shorten
                            example: Dolorum qui reiciendis corporis dolor consequatur ipsam.
            responses:
                "201":
                    description: Created response.
                    schema:
                        type: string
                        format: byte
            schemes:
                - http
    /openapi.json:
        get:
            tags:
                - UrlShortener
            summary: Download ./gen/http/openapi.json
            operationId: UrlShortener#/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
                - https
