swagger: "2.0"
info:
    title: GoTrim API Service
    description: URL shortening service written in Go
    version: 0.0.1
host: localhost:3050
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/v1/shorten:
        post:
            tags:
                - UrlShortener
            summary: CreateShortUrl UrlShortener
            operationId: UrlShortener#CreateShortUrl
            produces:
                - application/json
            parameters:
                - name: object
                  in: body
                  required: true
                  schema:
                    type: object
                    properties:
                        long_url:
                            type: string
                            description: URL to shorten
                            example: Consequatur et nihil quam temporibus.
            responses:
                "201":
                    description: Created response.
                    schema:
                        $ref: '#/definitions/URLShortenerCreateShortURLResponseBody'
            schemes:
                - http
    /openapi.json:
        get:
            tags:
                - UrlShortener
            summary: Download ./gen/http/openapi.json
            operationId: UrlShortener#/openapi.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
                - https
definitions:
    URLShortenerCreateShortURLResponseBody:
        title: URLShortenerCreateShortURLResponseBody
        type: object
        properties:
            long_url:
                type: string
                description: The long URL
                example: Provident enim.
            short_url:
                type: string
                description: The shorten URL
                example: Occaecati inventore vel et perspiciatis.
        example:
            long_url: Eius porro fugit.
            short_url: Autem autem assumenda earum.
